
set shortmess=I
set runtimepath
colorschem  darkblue
set go+=a
set mouse=ic
set sm
set et

"invisible characters
nnoremap \tl :set invlist list?<CR>
nmap <F2> \tl<cr>
map <f3> :WMToggle<cr>
map <F1> :vsplit new<CR> 
map <f4> :set spell!<cr>
map <f5> :mks! D:\Luc\vim.sess<cr>
map <f6> :source D:\Luc\vim.sess<cr>
map <f7> :set guioptions+=m<cr> 
map <f8> :set guioptions-=m<cr> 

nmap <f9> :tabnext<cr>
nnoremap \th :set invhls hls?<CR>
nmap <f10> \th<cr>


"line wrap
nnoremap \tm :set invwrap wrap?<CR>
nmap <f11> \tm<cr>

map <f12> :set number!<cr>
map <C-t> :tabnew<cr> 

set tabstop=4

com Vimrc :e $HOME/\.vimrc


set nobackup		" do not keep a backup file, use versions instead
