au  FileType  *  set nocindent
com Vimrc :e ~\.vimrc
set shortmess=I  "Sorry, No money for Uganda children
set go+=a 
let MultipleSearchMaxColors=256
set nobackup nowritebackup
colorscheme darkblue

au  FileType  *  set noautoindent
au  FileType  *  set nosmartindent
set et
set t_AB=[%?%p1%{8}%<%t%p1%{40}%+%e%p1%{92}%+%;%dm
set t_AF=[%?%p1%{8}%<%t%p1%{30}%+%e%p1%{82}%+%;%dm
set background=dark
set sm
set tags=tags;\
set incsearch
"set ignorecase
set title
set nocindent
set mouse=ic
set tabstop=4 shiftwidth=4 noexpandtab
set noswapfile

set diffopt+=iwhite
map <F1> :vsplit new<CR> 
map <F2> :set list!<cr>
map <F3> :tab new<cr>
map <f4> :set spell!<cr>
map <f5> :mks! ~\vim.sess<cr>
map <f6> :source ~\vim.sess<cr>
map <F7> :if exists("syntax_on") <Bar> syntax off <Bar> else <Bar> syntax on <Bar> endif <CR> 
map <F8> :set hlsearch! <CR>
map <F9> :tabnext<CR> 
map <F11> :set wrap!<CR> 
map <F12> :set number!<CR> 
if has('cscope')
  set cscopetag cscopeverbose
endif

